services:
  - type: web
    name: paywest-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: WAVE_WEBHOOK_SECRET
        sync: false
      - key: ORANGE_WEBHOOK_SECRET
        sync: false
